config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  get 'bookings' => 'application#booking'
  post 'bookings' => 'application#place_booking'
  get 'gallery' => 'application#gallery'
end

app/models/booking.rb
class Booking
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  ROOM_TYPES = ['Queen bed', 'Queen bed + single', 'Twin share']

  attr_accessor :name, :arrive, :depart, :room_type, :email, :phone_number, :message
  
  validates :name, :email, :arrive, :depart, :room_type, :phone_number, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validate do |booking|
    if booking.depart <= booking.arrive
      errors.add(:depart, 'date must be after arrival date')
    end
  end
  
  def initialize(attributes = {})
    @arrive = parse_date(default: Date.today,
                         day: attributes['arrive(3i)'],
                         month: attributes['arrive(2i)'],
                         year: attributes['arrive(1i)'])

    @depart = parse_date(default: Date.today + 1,
                         day: attributes['depart(3i)'],
                         month: attributes['depart(2i)'],
                         year: attributes['depart(1i)'])

    @name = attributes['name']
    @room_type = attributes['room_type']
    @email = attributes['email']
    @phone_number = attributes['phone_number']
    @message = attributes['message']
  end

  def parse_date(default: Date.today, day: nil, month: nil, year: nil)
    return default unless day && month && year
    Date.civil(year.to_i, month.to_i, day.to_i)
  end 
  
  def persisted?
    false
  end
end

app/models/picture.rb
class Picture
  attr_reader :name, :title, :description

  def initialize(name:, title:, description: nil)
    @name = name
    @title = title
    @description = description
  end

  def thumb_url
    "#{bucket}/#{dir}/#{@name}_s.jpg"
  end

  def url
    "#{bucket}/#{dir}/#{@name}.jpg"
  end

  def dir
    'images_gallery'
  end

  def bucket
    'http://s3.amazonaws.com/thepostmasterslodgings.co.nz'
  end

  def self.all
    [
      new(name: 'Postmasters-02', title: '', description: ''),
      new(name: 'Postmasters-03', title: '', description: ''),
      new(name: 'Postmasters-04', title: '', description: ''),
      new(name: 'Postmasters-05', title: '', description: ''),
      new(name: 'Postmasters-07', title: '', description: ''),
      new(name: 'Postmasters-09', title: '', description: ''),
      new(name: 'Postmasters-11', title: '', description: ''),
      new(name: 'Postmasters-13', title: '', description: ''),
      new(name: 'Postmasters-15', title: '', description: ''),
      new(name: 'Postmasters-17', title: '', description: ''),
      new(name: 'Postmasters-18', title: '', description: ''),
      new(name: 'Postmasters-19', title: '', description: ''),
      new(name: 'Postmasters-20', title: '', description: ''),
      new(name: 'Postmasters-22', title: '', description: ''),
      new(name: 'Postmasters-23', title: '', description: ''),
      new(name: 'Postmasters-24', title: '', description: ''),
      new(name: 'Postmasters-25', title: '', description: ''),
      new(name: 'Postmasters-26', title: '', description: ''),
      new(name: 'Postmasters-27', title: '', description: ''),
      new(name: 'Postmasters-28', title: '', description: ''),
      new(name: 'Postmasters-29', title: '', description: ''),
      new(name: 'Postmasters-30', title: '', description: ''),
      new(name: 'Postmasters-31', title: '', description: ''),
      new(name: 'Postmasters-32', title: '', description: ''),
      new(name: 'Postmasters-33', title: '', description: ''),
      new(name: 'Postmasters-35', title: '', description: ''),
      new(name: 'Postmasters-36', title: '', description: ''),
      new(name: 'Postmasters-38', title: '', description: ''),
    ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    expires_in 1.day, public: true
  end

  def booking
    @booking = Booking.new
  end

  def place_booking
    @booking = Booking.new(params[:booking])
    if @booking.valid?
      BookingMailer.confirm(@booking).deliver_now
      BookingMailer.book(@booking).deliver_now
      render 'pidgeon'
    else 
      render 'booking'
    end
  end

  def gallery
    expires_in 1.day, public: true
    @pictures = Picture.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def lightbox_thumb(picture)
    link_to(
      image_tag(
        picture.thumb_url,
        'alt' => picture.title,
        'data-caption' => picture.description
      ),
      picture.url,
      'name' => picture.name,
      'class' => 'th'
    )
  end
end

app/views/application/booking.html.erb
<div class="row">
  <div class="medium-6 columns">
    <nav class="show-for-small-only">
      <div class="icon-bar two-up">
        <%= link_to "#tariffs", class: "item" do %>
          <label>Tariffs</label>
        <% end %>
        <%= link_to "#contact", class: "item" do %>
          <label>Contact directly</label>
        <% end %>
      </div>
    </nav>

    <%= simple_form_for @booking do |f| %>
      <%= f.input :name %>
      <div class="row">
        <div class="small-6 columns">
          <%= f.input :arrive, as: :date,
            start_year: Date.today.year,
            end_year: Date.today.year + 2,
            order: [:day, :month, :year] %>
        </div>
        <div class="small-6 columns">
          <%= f.input :depart, as: :date,
            start_year: Date.today.year,
            end_year: Date.today.year + 2,
            order: [:day, :month, :year] %>
        </div>
      </div>
      <%= f.input :room_type, collection: Booking::ROOM_TYPES %>
      <%= f.input :email, as: :email %>
      <%= f.input :phone_number, as: :tel %>
      <%= f.input :message, as: :text %>
      <%= f.button :submit, 'Submit enquiry', class: 'expand' %>
    <% end %>
  </div>

  <div class="medium-6 columns">
    <div id="tariffs">
      <p>Queen rooms with ensuite from $150 per night.</p>
    </div>
    <div  id="contact">
      <p>Contact John or Dorothy</p>
        <ul>
          <li>
            <%= link_to "+64 (0) 9 405 7676", "tel:+64 (0) 9 405 7676" %>
          </li>
          <li>
            <%= link_to "e-mail", "mailto:stay@thepostmasterslodgings.co.nz" %>
          </li>
        </ul>
    </div>
    <div class="stamp"></div>
  </div>
</div>

app/views/application/gallery.html.erb
<div class="row">
  <div class="small-12 columns">
    <ul class="clearing-thumbs small-block-grid-3 medium-block-grid-6" data-clearing>
      <% @pictures.each do |picture| %>
        <li><%= lightbox_thumb(picture) %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/application/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <article>
      <div class="banner introduction"></div>
      <p>
        Nestled on the point above Rāwene township, with a panoramic view of the Hokianga Harbour from the balcony which runs around the building, the Postmasters Lodgings is a quaint, boutique B&B with a truly unique and unforgettable character. From the sumptuous bedrooms to the eclectic range of furniture and fittings evoking a bygone era, you will never forget the time you spent here. To see how idyllic this accommodation is just check out the <a href="/gallery">gallery</a> and read <a href="https://www.tripadvisor.com.au/Hotel_Review-g1466934-d1465272-Reviews-The_Postmasters_Lodgings-Rawene_Northland_Region_North_Island.html" target="_blank">Trip Advisor reviews</a>. All Queen rooms with ensuite from $120 per night.
      </p>
    </article>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <article>
      <div class="banner historic"></div>
      <p>
        The Postmasters as the name suggests, was the residence of the Postmaster himself in colonial times, giving you a truly historic experience.
      </p>
    </article>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <article>
      <div class="banner rawene"></div>
      <p>
        You will find Rawene and the Hokianga peaceful and untouched by the masses, the destination of choice for those seeking relaxation and natural beauty.
      </p>
      <p>
        Vists St Mary's Church, Clendon House, Omapare, Opononi or Tane Mahuta. All from Rawene.
      </p>
      <p>
        If you require excitement, Rawene happens to sit within striking distance of the popular Northland hotspots.
        <%= link_to "Getting here", "http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=The+Postmasters+Boutique+Hotel,+Rawene,+New+Zealand&sll=-35.391919,173.488626&sspn=0.032466,0.104456&ie=UTF8&hq=The+Postmasters+Boutique+Hotel,&hnear=Rawene,+Northland,+New+Zealand&ll=-35.387441,173.488541&spn=0.032468,0.071754&z=14&iwloc=A", { :target => "_blank" } %>
      </p>
    </article>
  </div>
</div>

app/views/application/pidgeon.html.haml
#stamp-sent{:style => "display:none;"}
  %p= Time.now
#pigeon{:style => "display:none;"}
%p booking sent

app/views/layouts/_google_analytics.html.erb
<!-- Google Analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
   (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
   m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
   })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-17751156-3', 'auto');
  ga('send', 'pageview');
</script>
<!-- End Google Analytics -->

app/views/layouts/_top_bar.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">The Postmasters Lodgings</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <%= active_link_to 'Full Gallery', gallery_path, wrap_tag: :li %>
      <%= active_link_to 'Booking Enquiry', bookings_path, wrap_tag: :li %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name= "description", content="The Postmasters Lodgings" />
    <meta name= "keywords" content="Boutique Accommodation Rawene New Zealand" />
    <link href="/favicon.png" rel="shortcut icon" />
    <title>The Postmasters Lodgings | Boutique Accommodation Rawene New Zealand</title>
    <%= stylesheet_link_tag "application" %>
    <%= csrf_meta_tags %>
    <% if Rails.env.production? %>
      <%= render partial: 'layouts/google_analytics' %>
    <% end %>
  </head>
  <body>
    <div class="row">
      <div class="large-12 columns">
        <%= render partial: 'layouts/top_bar' %>
        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
  </body>
</html>